### ISSUE TITLE
Doubts 

### ISSUE THREAD

**Issue by BhJaipal** [ameypte/Projects#1]
How are .c files executed in terminal
Doesn't that `search:` in add_contact method in contact management system causes error

If I do
```c
#include <stdio.h>
#include <string.h>

int main() {
    string name;
    scanf("Enter your name: %s", name);
    printf("Hello %s", name);
}
```
Will it work as
```python
name = str(input("Enter your name: "))
print("Hello ", name)
```
Or will it cause an error

**Comment by ameypte** [comment]
You don't need to use str() because input is already in String but this will also works fine

**Comment by BhJaipal** [comment]
What does `search:` mean
